// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
	"encoding/json"
)

type App struct {
	ID     int64
	Token  sql.NullString
	Userid int64
}

type Log struct {
	ID        int64
	Text      string
	Apptoken  string
	Level     string
	Createdat sql.NullTime
	Updatedat sql.NullTime
	Context   json.RawMessage
	Ip        sql.NullString
	Tags      json.RawMessage
}
