// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: tasks.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addComment = `-- name: AddComment :exec
INSERT INTO task_comments (message, sender_id, task_id, createdat, updatedat) VALUES ($1, $2, $3, now(), now())
`

type AddCommentParams struct {
	Message  string
	SenderID int32
	TaskID   uuid.UUID
}

func (q *Queries) AddComment(ctx context.Context, arg AddCommentParams) error {
	_, err := q.db.ExecContext(ctx, addComment, arg.Message, arg.SenderID, arg.TaskID)
	return err
}
