CREATE TABLE logs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  text TEXT NOT NULL,
  appId BIGINT NOT NULL REFERENCES apps(id) ON DELETE CASCADE,
  level VARCHAR(16) NOT NULL DEFAULT 'error',
  createdAt TIMESTAMP DEFAULT(NOW()),
  updatedAt TIMESTAMP DEFAULT(NOW())
);

CREATE TABLE apps (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  token TEXT,
  userId BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);