CREATE TABLE logs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  text TEXT NOT NULL,
  appToken TEXT NOT NULL REFERENCES apps(token) ON DELETE CASCADE,
  level VARCHAR(16) NOT NULL DEFAULT 'error',
  createdAt TIMESTAMP DEFAULT(NOW()),
  updatedAt TIMESTAMP DEFAULT(NOW()),
  context JSON
);

CREATE TABLE apps (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  token TEXT,
  userId BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);